from pathlib import Path

from rocketsmith.prusaslicer.models import (
    ConfigEntry,
    ConfigListResult,
    ConfigSettings,
    ConfigType,
)

# Default config root: prusaslicer/configs/ relative to the working directory.
DEFAULT_CONFIG_PATH = Path("prusaslicer") / "configs"


def _config_dir(base: Path, config_type: ConfigType) -> Path:
    return base / config_type.value


def _config_file(base: Path, config_type: ConfigType, name: str) -> Path:
    return _config_dir(base, config_type) / f"{name}.ini"


def _parse_ini(path: Path) -> dict[str, str]:
    """Parse a flat PrusaSlicer .ini file into a key-value dict."""
    settings: dict[str, str] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                settings[key.strip()] = value.strip()
    return settings


def _write_ini(path: Path, settings: dict[str, str]) -> None:
    """Write a flat PrusaSlicer .ini file from a key-value dict."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by RocketSmith\n")
        for key in sorted(settings):
            f.write(f"{key} = {settings[key]}\n")


def list_configs(
    base: Path,
    config_type: ConfigType | None = None,
) -> ConfigListResult:
    """List all .ini configs, optionally filtered by type."""
    types = [config_type] if config_type else list(ConfigType)
    entries: list[ConfigEntry] = []
    for ct in types:
        d = _config_dir(base, ct)
        if not d.exists():
            continue
        for ini_file in sorted(d.glob("*.ini")):
            entries.append(
                ConfigEntry(name=ini_file.stem, config_type=ct, path=ini_file)
            )
    return ConfigListResult(configs=entries, count=len(entries))


def show_config(base: Path, config_type: ConfigType, name: str) -> ConfigSettings:
    """Read and return the settings of a named config."""
    path = _config_file(base, config_type, name)
    if not path.exists():
        raise FileNotFoundError(f"Config not found: {path}")
    return ConfigSettings(
        name=name,
        config_type=config_type,
        path=path,
        settings=_parse_ini(path),
    )


def create_config(
    base: Path,
    config_type: ConfigType,
    name: str,
    settings: dict[str, str],
) -> ConfigEntry:
    """Create a new config file. Raises FileExistsError if it already exists."""
    path = _config_file(base, config_type, name)
    if path.exists():
        raise FileExistsError(f"Config already exists: {path}")
    _write_ini(path, settings)
    return ConfigEntry(name=name, config_type=config_type, path=path)


def set_config(
    base: Path,
    config_type: ConfigType,
    name: str,
    settings: dict[str, str],
) -> ConfigSettings:
    """Merge settings into an existing config (creates it if absent)."""
    path = _config_file(base, config_type, name)
    existing: dict[str, str] = _parse_ini(path) if path.exists() else {}
    existing.update(settings)
    _write_ini(path, existing)
    return ConfigSettings(
        name=name,
        config_type=config_type,
        path=path,
        settings=existing,
    )


def delete_config(base: Path, config_type: ConfigType, name: str) -> ConfigEntry:
    """Delete a config file. Raises FileNotFoundError if it doesn't exist."""
    path = _config_file(base, config_type, name)
    if not path.exists():
        raise FileNotFoundError(f"Config not found: {path}")
    entry = ConfigEntry(name=name, config_type=config_type, path=path)
    path.unlink()
    return entry
