name: ubuntu

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"

      - name: Install project dependencies
        run: uv sync --locked --dev

      - name: Install rocketsmith package locally
        run: uv pip install -e .

      - name: Install OpenRocket
        run: uv run rocketsmith openrocket install

      - name: Install PrusaSlicer
        run: uv run rocketsmith prusaslicer install

      - name: Run tests
        run: uv run pytest tests/openrocket tests/prusaslicer --cov=rocketsmith --cov-report xml --junitxml=junitxml -o junit_family=legacy
        env:
          NO_COLOR: 1
          TERM: dumb

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
